# Generated by Django 4.2.7 on 2023-12-08 05:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0004_user_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_information',
            name='user',
            field=models.ForeignKey(default= 1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_information',
            name='user_profile_picture',
            field=models.ImageField(blank=True, upload_to=main_page.models.file_user_picture_location, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='picture',
            field=models.ImageField(upload_to=main_page.models.picture_upload_location, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
