# Generated by Django 4.2.7 on 2024-01-10 01:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0008_alter_comments_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_information',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_information',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_pic', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='user_profile_picture',
            field=models.ImageField(blank=True, default='static/default-profile.png', upload_to=main_page.models.file_user_picture_location, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
