# Generated by Django 4.2.7 on 2024-01-17 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_page', '0009_remove_user_information_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_friends',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='friends', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('friends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friends', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request', to=settings.AUTH_USER_MODEL)),
                ('sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
