# Generated by Django 4.2.7 on 2024-01-24 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0012_rename_friend_request_friend_request_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_friends',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_friends',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='friends_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
