# Generated by Django 4.2.7 on 2024-01-30 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_report_post_report_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_main',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.comments_post'),
        ),
    ]
