# Generated by Django 4.2.7 on 2024-02-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_alter_report_main_user_alter_report_post_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
