# Generated by Django 4.2.7 on 2023-11-27 21:00

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_userpost_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_picture', models.ImageField(upload_to=main_page.models.file_user_picture_location)),
            ],
        ),
    ]
