# Generated by Django 4.2.7 on 2024-02-27 00:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0019_rename_reportedposts_reportedpost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report_post',
            unique_together={('user', 'post')},
        ),
    ]
