# Generated by Django 4.2.7 on 2024-03-16 20:07

import django.core.validators
from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_reportcomment_reportedcomment_delete_report_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='picture',
            field=models.ImageField(upload_to=main_page.models.picture_upload_location, validators=[django.core.validators.validate_image_file_extension, main_page.models.image_validation]),
        ),
    ]
