# Generated by Django 4.2.7 on 2023-12-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0004_tip_gps_cords_lat_tip_gps_cords_long_tip_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='icon',
            field=models.TextField(default='golf'),
        ),
    ]
