# Generated by Django 4.2.7 on 2023-12-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0005_alter_tip_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gps_cords_lat',
            field=models.FloatField(default=-119.4856),
        ),
        migrations.AddField(
            model_name='course',
            name='gps_cords_long',
            field=models.FloatField(default=39.3247),
        ),
    ]
