# Generated by Django 4.2.7 on 2024-01-17 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0010_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_friends',
            name='request',
        ),
        migrations.RemoveField(
            model_name='user_friends',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='user_friends',
            name='friends',
        ),
        migrations.CreateModel(
            name='friend_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request', to=settings.AUTH_USER_MODEL)),
                ('sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user_friends',
            name='friends',
            field=models.ManyToManyField(related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
