# Generated by Django 4.2.7 on 2024-01-24 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0011_remove_user_friends_request_remove_user_friends_sent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='friend_request',
            new_name='friend_request_model',
        ),
        migrations.AlterField(
            model_name='user_friends',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
