# Generated by Django 4.2.7 on 2024-02-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0018_reportedposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportedPosts',
            new_name='ReportedPost',
        ),
    ]
