# Generated by Django 4.2.7 on 2023-12-07 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('tip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('hole_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.holedetail')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
