# Generated by Django 4.2.7 on 2023-12-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_alter_score_hole_1_alter_score_hole_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='gps_cords_lat',
            field=models.FloatField(default=-119.4856),
        ),
        migrations.AddField(
            model_name='tip',
            name='gps_cords_long',
            field=models.FloatField(default=39.3247),
        ),
        migrations.AddField(
            model_name='tip',
            name='icon',
            field=models.TextField(default='theatre'),
        ),
    ]
