# Generated by Django 4.2.7 on 2024-02-08 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0006_course_gps_cords_lat_course_gps_cords_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='date_played',
        ),
        migrations.AddField(
            model_name='score',
            name='datetime_played',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
