# Generated by Django 4.2.7 on 2024-03-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0007_remove_score_date_played_score_datetime_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
