# Generated by Django 4.2.7 on 2023-12-05 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField()),
                ('hole_1', models.IntegerField()),
                ('hole_2', models.IntegerField()),
                ('hole_3', models.IntegerField()),
                ('hole_4', models.IntegerField()),
                ('hole_5', models.IntegerField()),
                ('hole_6', models.IntegerField()),
                ('hole_7', models.IntegerField()),
                ('hole_8', models.IntegerField()),
                ('hole_9', models.IntegerField()),
                ('total_9', models.IntegerField()),
                ('hole_10', models.IntegerField()),
                ('hole_11', models.IntegerField()),
                ('hole_12', models.IntegerField()),
                ('hole_13', models.IntegerField()),
                ('hole_14', models.IntegerField()),
                ('hole_15', models.IntegerField()),
                ('hole_16', models.IntegerField()),
                ('hole_17', models.IntegerField()),
                ('hole_18', models.IntegerField()),
                ('round_total', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.course')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoleDetail',
            fields=[
                ('hole_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hole_number', models.IntegerField()),
                ('par_number', models.IntegerField()),
                ('yardage', models.IntegerField()),
                ('handicap', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.course')),
            ],
        ),
    ]
