# Generated by Django 4.2.7 on 2023-12-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='hole_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_14',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_15',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_16',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_17',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_18',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='round_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_9',
            field=models.IntegerField(default=0),
        ),
    ]
